# Generated by Django 3.1.5 on 2021-01-29 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=50)),
                ('project1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fav1', to='cyas.project')),
                ('project2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fav2', to='cyas.project')),
            ],
        ),
    ]
